# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db076179329dfb15a3cbedddee23feb800f3ee20fdbb73a08a3eb4480bddc3dde3e0b4eddcadadf0b2a9d8a324bca12e5594dbfb170a1d82bdac8c1818f1d504

test:
  secret_key_base: e1b7b37220bcb09ccbbcbea5670178571005d5577eaf96ecd94dc8067c917b12271d1d4de62d8cb3dfe7e712129ef114b0130a426c3e6785d40f662425827095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
